yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/author/', views.author, name='author'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    import debug_toolbar


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы пользователей'


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты пользователей'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
        help_text='Автор комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        related_name='comments',
        verbose_name='Пост комментария',
        help_text='Пост комментария'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор подписки',
        help_text='Автор подписки'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [models.UniqueConstraint(
            name='unique_follow',
            fields=['author', 'user'],
        )]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'group',
            'text',
            'image'
        )
        help_texts = {
            'group': 'Введите группу для поста',
            'text': 'Текст поста',
            'image': 'Картинка поста'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Group, Post, Follow, User


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('group').all()
    paginator = Paginator(post_list, settings.POSTS_NUMBER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'index': True,
        'follow': False,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, settings.POSTS_NUMBER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, settings.POSTS_NUMBER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        follower = request.user
        following = (
            Follow.objects.filter(author=author).
            filter(user=follower).exists()
        )
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def author(request):
    author = get_object_or_404(User, username=request.user.username)
    return profile(request, author)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', request.user.username)
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'is_edit': False}
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST' and form.is_valid():
        post = form.save()
        return redirect('posts:post_detail', post_id)
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'is_edit': True}
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    post_list = Post.objects.filter(
        author__following__user=request.user
    )
    paginator = Paginator(post_list, settings.POSTS_NUMBER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'index': False,
        'follow': True,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        follow, created = Follow.objects.get_or_create(
            author=author,
            user=request.user
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    ex_follow = Follow.objects.filter(user=request.user).filter(author=author)
    ex_follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block page_title %} 

  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %} 

 {{group.title}}
 
{% endblock %}

{% block content %} 

 <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактирование поста
                {% else %}
                  Новый пост
                {% endif %}            
              </div>
              <div class="card-body">

                <form method="post" enctype= "multipart/form-data"%}>

                  {% csrf_token %}
                          
                    {% for field in form %}
                      <div>
                        {{ field.help_text }}                  
                        <span class="required text-danger" ></span>                  
                      </div>
                      <div>
                        {{ field }}                 
                        <span class="required text-danger" >*</span>                
                      </div>
                    {% endfor %} 

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %} 
                    </button>
                  </div>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% cache 20 sidebar %}

{% block page_title %}  Подписки {{group.title}} {% endblock %}

{% block page_header %} <h1> Посты избранных авторов </h1> {% endblock %}

{% block content %} 

    {% include 'posts/includes/switcher.html' %}

    {% for post in page_obj %}

            <ul>
              <li>
                <span style="font-weight:bold">Автор:</span> {{ post.author.get_full_name }}
              </li>
              <li>
                <span style="font-weight:bold">Дата публикации:</span> {{ post.pub_date|date:"d E Y" }}
              </li>
              <li>
                <span style="font-weight:bold">Группа:</span> {{ post.group.title }}
              </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <a href="{% url 'posts:post_detail' post.id %}">детали</a> 
            &nbsp
            {% if post.group %}      
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
            {% endif %}
              &nbsp
              <a href="{% url 'posts:profile' post.author.username %}">страница автора</a>    
          {% if not forloop.last %}<hr>{% endif %}
          
    {% endfor %} 

    {% include 'posts/includes/paginator.html' %}

{% endblock %}
{% endcache %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block page_title %}  Записи сообщества {{group.title}} {% endblock %}

<hr>

{% block page_header %} <h1> {{group.title}} </h1> <hr> <p> {{group.description}} </p> <hr> {% endblock %}

{% block content %} 
  {% load thumbnail %}
    {% for post in page_obj %}

            <ul>
              <li>
                <span style="font-weight:bold">Автор:</span> {{ post.author.get_full_name }}
              </li>
              <li>
                <span style="font-weight:bold">Дата публикации:</span> {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <a href="{% url 'posts:post_detail' post.id %}">детали</a> 
            &nbsp
            <a href="{% url 'posts:profile' post.author.username %}">страница автора</a>

        {% if not forloop.last %}<hr>{% endif %}

    {% endfor %} 

    {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% cache 20 sidebar %}

{% block page_title %}  Главная страница {% endblock %}

{% block page_header %} <h1> Актуальные посты </h1> {% endblock %}

{% block content %} 

  {% include 'posts/includes/switcher.html' %}

    {% for post in page_obj %}
            <ul>
              <li>
                <span style="font-weight:bold">Автор:</span> {{ post.author.get_full_name }}
              </li>
              <li>
                <span style="font-weight:bold">Дата публикации:</span> {{ post.pub_date|date:"d E Y" }}
              </li>
              <li>
                <span style="font-weight:bold">Группа:</span> {{ post.group.title }}
              </li>
            </ul>
            <p>{{ post.text|linebreaksbr }}</p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <a href="{% url 'posts:post_detail' post.id %}">детали</a> 
            &nbsp
            {% if post.group %}      
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы   </a>
            {% endif %}
              &nbsp
              <a href="{% url 'posts:profile' post.author.username %}">страница автора</a>      
          {% if not forloop.last %}<hr>{% endif %}          
    {% endfor %} 

    {% include 'posts/includes/paginator.html' %}

{% endblock %}
{% endcache %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block page_title %}  Пост пользователя {{ author.get_full_name }} {% endblock %}

{% block content %} 

{% load thumbnail %}
  <main>
      <div class="row">
        <aside class="col-12 col-md-4">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <span style="font-weight:bold">Дата публикации:</span> {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}  
              <li class="list-group-item">
                <span style="font-weight:bold">Группа:</span> {{ post.group.title }} <br>
                <a href="{% url 'posts:group_posts' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %} 
              <li class="list-group-item">
                <span style="font-weight:bold">Автор:</span> {{ post.author.get_full_name }}
                <br>
                  Всего постов автора:  <span > {{ post.author.posts.count }} </span>
                <br>
              <a href={% url 'posts:profile' post.author.username %}>
                все посты пользователя
              </a>
              </li>
          </ul>
        </aside>
        <article class="col-12 col-md-8">
      
          <p>
           {{ post.text }}
          </p>

          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}

        </article>

        {% include 'posts/includes/comments.html' %}

      </div> 
    </main>

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 

{% block page_title %}  Профайл пользователя {{ author.get_full_name }} {% endblock %} 

{% block page_header %} <h1> {{ author.get_full_name }} </h1> <hr> <p> Всего постов: {{ author.posts.count }} </p> <hr> {% endblock %}

{% block content %} 
  {% load thumbnail %}
    <main>
      <div class="container py-5">        
 
     

            {% if request.user.is_authenticated %}

              {% if following %}
                <a
                  class="btn btn-lg btn-light"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                  Отписаться
                </a>
              {% else %}
                <a
                  class="btn btn-lg btn-primary"
                  href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                  Подписаться
                </a>
              {% endif %}
              
            {% endif %}
        <hr>
            {% for post in page_obj %}

            <ul>
              <li>
                <span style="font-weight:bold">Автор:</span> {{ author.get_full_name }}
              </li>
              <li>
                <span style="font-weight:bold">Дата публикации:</span> {{ post.pub_date|date:"d E Y" }}
              </li>

                {% if post.group %} 
                    <li>
                        <span style="font-weight:bold">Группа:</span> {{ post.group.title }}
                    </li>
                {% endif %} 

            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <a href="{% url 'posts:post_detail' post.id %}">детали</a> 
            &nbsp
            <a href="{% url 'posts:post_edit' post.id %}">редактировать</a> 
            &nbsp
            {% if post.group %}      
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
            {% endif %}      
          {% if not forloop.last %}<hr>{% endif %}
          
    {% endfor %} 

    {% include 'posts/includes/paginator.html' %}

{% endblock %}